# Site settings
title: Aaron's Ramblings
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This is a place for all of my ramblings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://geekgonecrazy.com" # the base hostname & protocol for your site
twitter_username: geekgonecrazy
github_username:  geekgonecrazy
mastodon_instance: fosstodon.org
mastodon_username: geekgonecrazy

# Build settings
markdown: kramdown
permalink: pretty
kramdown:
  input: GFM
  
comments: false

# jekyll tagging
tag_page_layout: tag_index
tag_page_dir: tags
tag_feed_dir: tags

gems: 
  - jemoji
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-tagging

include: [".well-known"]
