baseURL: "https://aaronogle.dev"
languageCode: "en-us"
title: "Aaron Ogle"
theme: "hugo-notepadium"
permalinks:
  posts: "/:year/:month/:day/:title"
params:
  style: "dark"
  nav:
    custom:
      - title: "Home"
        url: "/"
      - title: "About"
        url: "/about"
outputs:
  home:
  - HTML
  - Feed
mediaTypes:
  application/rss+xml:
    suffixes:
      - xml
outputFormats:
  Feed:
    baseName: feed
    isPlainText: false
    mediaType: application/rss+xml
  
