baseURL: "https://geekgonecrazy.com/"
languageCode: "en-us"
title: "Aaron's Ramblings"
theme: "hugo-notepadium"
permalinks:
  posts: "/:year/:month/:day/:title"
params:
  style: "dark"
  nav:
    custom:
      - title: "Home"
        url: "/"
      - title: "About"
        url: "/about"