name: github pages

on:
  push:
    branches:
    - source

jobs:
  build-deploy:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout Source
      uses: actions/checkout@master
      with:
        submodules: true
    - name: Publish Site
      uses: chabad360/hugo-gh-pages@master
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        # Use if you have a custom domain for your site.
        cname: aaronogle.dev
        # Use if your site is not hosted on the gh-pages branch.
        branch: master
        hugoVersion: extended_0.72.0
        # Use if your site requires a specific version of Hugo
        # Append "extended_" to the begining to use Hugo Extended
        args: --gc --minify --cleanDestinationDir
        # Use if you want to pass some custom arguments to Hugo
